// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Case02_5Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test55() {
    driver.get("http://45.144.164.182:8080/");
    driver.manage().window().setSize(new Dimension(1112, 819));
    driver.findElement(By.cssSelector("#post-36 > .titles-16 > a")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("LOVE");
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("author")).click();
    {
      WebElement element = driver.findElement(By.id("author"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("author")).sendKeys("m");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("m@gmail.com");
    driver.findElement(By.id("email")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("e");
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("author")).click();
    {
      WebElement element = driver.findElement(By.id("author"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("commentform")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("m@gmail.com\\");
    driver.findElement(By.id("email")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("email")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("email")).sendKeys("m@gmail.com");
    driver.findElement(By.id("commentform")).click();
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("author")).click();
    {
      WebElement element = driver.findElement(By.id("author"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("r");
    driver.findElement(By.id("submit")).click();
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("email")).click();
    driver.findElement(By.cssSelector(".g-30")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("t");
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("p\\n");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("« Back")).click();
  }
}
