// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Case05Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkoutfail2() {
    driver.get("http://45.144.164.182:8080/");
    driver.manage().window().setSize(new Dimension(784, 816));
    driver.findElement(By.linkText("Add to cart")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    driver.findElement(By.cssSelector(".header-wrap-right #cart-bag > .fa:nth-child(1)")).click();
    driver.findElement(By.linkText("Checkout")).click();
    driver.findElement(By.id("billing_first_name")).click();
    driver.findElement(By.id("billing_first_name")).sendKeys("Jaemin");
    driver.findElement(By.id("billing_last_name")).click();
    driver.findElement(By.id("billing_last_name")).sendKeys("Na");
    driver.findElement(By.id("billing_company")).click();
    driver.findElement(By.id("billing_company")).sendKeys("nct dream");
    driver.findElement(By.id("billing_address_1")).click();
    driver.findElement(By.id("billing_address_1")).sendKeys("999");
    driver.findElement(By.id("billing_city")).click();
    driver.findElement(By.id("billing_city")).sendKeys("พุทธมณฑล");
    driver.findElement(By.id("select2-billing_state-container")).click();
    driver.findElement(By.id("billing_postcode")).click();
    driver.findElement(By.id("billing_postcode")).sendKeys("abcd");
    driver.findElement(By.id("place_order")).click();
    driver.findElement(By.id("billing_phone")).click();
    driver.findElement(By.id("billing_phone")).sendKeys("028496000");
    driver.findElement(By.id("billing_email")).click();
    driver.findElement(By.id("billing_email")).sendKeys("jaemin@gmail.com");
    driver.findElement(By.name("checkout")).click();
    driver.findElement(By.id("place_order")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".owl-item:nth-child(6) .attachment-woocommerce_thumbnail"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".header-wrap-right #cart-bag > .fa:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".header-wrap-right #cart-bag > .fa:nth-child(1)")).click();
    driver.findElement(By.linkText("Checkout")).click();
    driver.findElement(By.id("customer_details")).click();
    driver.findElement(By.id("billing_postcode")).sendKeys("แจมิน");
    driver.findElement(By.id("billing_phone")).click();
    driver.findElement(By.id("customer_details")).click();
    driver.findElement(By.id("billing_phone")).sendKeys("wwwwww");
    driver.findElement(By.id("order_review_heading")).click();
    driver.findElement(By.id("place_order")).click();
    driver.findElement(By.cssSelector(".col-1")).click();
    driver.findElement(By.id("billing_phone")).sendKeys("028496000");
    driver.findElement(By.id("billing_email")).click();
    {
      WebElement element = driver.findElement(By.id("customer_details"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("customer_details"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("customer_details"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("customer_details")).click();
    driver.findElement(By.id("billing_email")).sendKeys("zzzzz");
    driver.findElement(By.id("order_review_heading")).click();
    driver.findElement(By.id("place_order")).click();
    {
      WebElement element = driver.findElement(By.id("place_order"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("billing_postcode")).click();
    driver.findElement(By.id("billing_postcode")).sendKeys("10700");
    driver.findElement(By.id("billing_phone")).click();
    {
      WebElement element = driver.findElement(By.id("billing_email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("billing_email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("billing_email"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("billing_email")).click();
    driver.findElement(By.id("billing_email")).sendKeys("jaemin@gmail.com");
    driver.findElement(By.id("ship-to-different-address-checkbox")).click();
    driver.findElement(By.id("customer_details")).click();
    driver.findElement(By.id("shipping_postcode")).sendKeys("พพพพพ");
    driver.findElement(By.id("customer_details")).click();
    driver.findElement(By.id("shipping_postcode")).sendKeys("qqqq");
    driver.findElement(By.id("place_order")).click();
  }
}
