// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Case02_3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test53() {
    driver.get("http://45.144.164.182:8080/");
    driver.manage().window().setSize(new Dimension(1112, 819));
    driver.findElement(By.cssSelector("#post-35 > div:nth-child(1)")).click();
    driver.findElement(By.linkText("Clothing Blog Section Contains")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("Y_Y");
    driver.findElement(By.id("author")).click();
    driver.findElement(By.id("author")).sendKeys("maipai");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("maipai@gmail.com");
    driver.findElement(By.id("url")).click();
    driver.findElement(By.id("url")).sendKeys("https://www.google.com/");
    driver.findElement(By.cssSelector("label:nth-child(2)")).click();
    driver.findElement(By.id("submit")).click();
  }
}
