// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Case01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  // : ทดสอบเรื่องการเข้าสู่ระบบ (Login) ของระบบ และการลืมรหัสผ่านของผู้ใช้งาน (Lost Password) แต่เนื่องจากในความเป็นจริงแล้วก่อนที่ผู้ใช้งานจะทำการเข้าสู่ระบบ (Login) ได้ระบบควรที่จะให้ผู้ใช้งานลงทะเบียน (Register) ก่อน
  @Test
  public void test1() {
    driver.get("http://45.144.164.182:8080/");
    driver.manage().window().setSize(new Dimension(1342, 804));
    driver.findElement(By.cssSelector(".fa-sign-in:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".fa-spinner")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("neadnapa.tha@student.mahidol.edu");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("neadnapa.tha");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("TEST12345");
    driver.findElement(By.cssSelector(".show-password-input")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    {
      WebElement element = driver.findElement(By.id("username"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    {
      WebElement element = driver.findElement(By.id("username"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("neadnapa.tha@student.mahidol.edu");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("test12345");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("test12345");
    driver.findElement(By.id("rememberme")).click();
    driver.findElement(By.name("login")).click();
    // Lost password
    driver.findElement(By.linkText("Lost your password?")).click();
    driver.findElement(By.cssSelector(".woocommerce-Button")).click();
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("neadnapa.tha");
    driver.findElement(By.cssSelector(".bread-title")).click();
    driver.findElement(By.cssSelector(".woocommerce-Button")).click();
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("neadnapa.tha@student.mahidol.edu");
    driver.findElement(By.cssSelector(".woocommerce-Button")).click();
  }
}